;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


(define (fib-iter a b n)
    (if (> n 2) (fib-iter b (+ a b) (- n 1)) b))

(define (sum-even-iter sum count n)
    (let ((term (fib count)))
        (if (< term n) 
            (sum-even-iter (if (= (remainder term 2) 0) 
                                (+ sum term) sum ) (+ count 1) n) sum)))

(define (sum-even  n) (sum-even-iter 0 1 n))

;(define (fib n) (fib-iter 1 1 n))

(sum-even 4000000)



